# Conclusion

The central topic of our project is climate change, an immensely important, complicated, and dynamic field that has implications in almost every aspect of the human world.  And while we certainly did not provide a comprehensive analysis of all of the factors that contributes/relates to climate change, we did make an attempt at a subset of those features.  Throughout this project, we explored 12 different questions (ranging from the analysis of a country's GDP to the relationship between sea level change and sea ice volume).  Some of our main takeaways are as follows.

At a very high level, the GDP, population, air pollution, carbon dioxide concentrations, temperature change, mean sea level change, greenhouse gas concentrations, forest area, and agricultural area of the top 11 GDP countries have all seen significant changes over the past several decades.  These changes can be attributed to a variety of factors, including but not limited to human activities such as the burning of fossil fuels and natural processes such as the inherent seasonality of climate data.  Additionally, there are complex relationships between these different features, such as the relationship between GDP and temperature change, population and temperature change, and sea level change and sea ice concentration. These complex relationship individually can warrant years of research to fully understand and develop, therefore, we have only provided a brief introduction/analysis to these questions.  Despite the relative simplicity of our research compared to those in academia, we certainly hope that this project gave the you (the audience) an indication of how our beloved Earth is changing (mostly for the worse), and that steps are needed to ensure the survival of this blue, beautiful, and unique planet.  

There are several limitations not just to our project, but to the study of climate change as whole.  One of the major challenges is the complexity of the Earth's climate system, which is influenced by a wide range of factors including atmospheric conditions, ocean currents, and human activity. As a result, it can be difficult to predict how the climate will change in the future, and the exact impacts of these changes are often difficult to quantify.  Another limitation is the limited availability of long-term data on the climate, which makes it difficult to accurately assess historical trends and patterns. Additionally, the study of climate change often involves complex mathematical models and computer simulations, which can be subject to errors and uncertainties.  Finally, with this only being a semester in length, there was not an abundance of time for our group to explore all of the complex climate models or uncertainties in climate observations, therefore, our exploration is admittedly focused more on breadth, rather than depth.  

Due to these limitations, there are a plethora of potential future directions that this project can take.  For example, our group wanted to include a variety of different plots (other than just time series and boxplots) to represent the climate data.  Therefore, one potential future step is to transform and translate the data (in a proper and climate approved manner) in order to explore other medians of representation.  Furthermore, with climate data being so inherently noisy and u=subjected to errors, in the future, we could potentially consult climate research to learn how to deal with this type of data, rather than just simply discarding or imputing missing values.  

In conclusion, this project was an immense learning experience for our group, not just for climate change, but about the techniques of exploratory data analysis and visualization as well.  One recurring realization and lesson that seems to be present everywhere in the field of data science is that 80% of the work will be cleaning and transforming data.  This was most definitely the case in our project, as the process to join different data sets on the common fields of countries and years required quite a bit of transformation.  Nonetheless, as group, we are proud of the work we put into this project, and we hope the audience learned something new/interesting about climate change.  Thank you!

