# Proposal

## Research topic
Climate change is commonly referred to as the long term change in Earth's climate and weather patterns, and although these changes may be naturally occurring, since the 1800s, artificial human activities have been the main driver.  Throughout the scientific community, climate change is no longer considered to be a "future" issue, in fact, changes to Earth's climate driven by the increased emissions of fossil fuels are already having widespread effects on the environment: rising global temperatures, shrinking ice sheets and glaciers, rising sea levels, depleting ozone, and extreme weather events such as droughts, heatwaves, and excessive rainfall.  Most, if not all of these changes can be attributed to quantifiable human factors, therefore, our project - Climate Change Analysis - seeks to explore and visualize these relationships.  For example, by examining time series data (by country) on atmospheric carbon dioxide concentrations, mean temperature change, mean sea level change, energy consumption, air pollution ...etc, we are hopefully able to gain some valuable insights on what each individual country's "contribution" to climate change is.  Furthermore, by bringing in additional data such as the population, Gross Domestic Product (GDP), and other characteristics of those same countries, a more significant relationship can potentially be realized.  Understanding that much of the world has been plagued by a global pandemic during the last couple of years (which undoubtedly affects human activity), we also seek to compare metrics such as air pollution before and during COVID-19.  Lastly, with the adoption of the Paris Agreement, focusing on climate change adaptation and finance, in 2015, we are interesting in seeing which countries actually implemented the proposed strategies to mitigate their climate contributions.  

## Data availability

With climate change being such a forefront issue in the world today, there are vast amounts of data available on this subject, from a multitude of sources such as NASA, NOAA, and other climate organizations around the world.  Therefore, our group is planning to combine multiple data sets to output a more comprehensive analysis.  The following sections will denote the data sets we plan on using, as well as any relevant information regarding the data source and data collection process.  

### Annual Surface Temperature Change

https://climatedata.imf.org/datasets/4063314923d74187be9596f10d034914/explore 
https://www.fao.org/faostat/en/#data/ET 

This data set showcases the annual estimates of mean surface temperature change from 1961 to 2021 by country, with respect to a baseline climatology (defined as the period of 1951 to 1980).  The data comes from the Food and Agriculture Organization of the United Nations (FAO), and is updated annualy, as it is a yearly time series data.  The data is downloadable as a csv file, which can easily be read into R Studios.

### Atmospheric Carbon Dioxide Concentrations

https://climatedata.imf.org/datasets/9c3764c0efcc4c71934ab3988f219e0e/explore 
https://gml.noaa.gov/ccgg/trends/ 

This data set showcases the monthly atmospheric carbon dioxide levels, presented at the World level in parts per million (ppm).  The data comes from the National Oceanic and Atmopsheric Administration (NOAA), and is updated monthly.  Like the previous data set, this can be downloaded as a csv file, and easily read into R Studios.


### Change in Mean Sea Levels
https://climatedata.imf.org/datasets/b84a7e25159b4c65ba62d3f82c605855/explore 

This data set showcases the changes in mean sea levels across 24 regions of the world, and the specific measurements (in millimeters) are estimated from satellite radar altimeters.  This data comes from NOAA, and its time series information is presented from 1992 to 2022, with 3/4 data points for every month in between.  Like the previous data set, this can be downloaded as a csv file, and easily read into R Studios.

### Climate Related Disasters Frequency
https://climatedata.imf.org/datasets/b13b69ee0dde43a99c811f592af4e821/explore 

This data set showcases the trend in the number of climate related natural disasters each year, by country.  The data comes from the Emergency Events Database, which covers disasters that killed more than ten people, affected more than a hundred people, led to the declaration of a state of emergency, and led to a call for international assistance.  This time series data is updated yearly, and can be downloaded as a csv file, easily read into R Studios.  

### Change in Sea Ice Volume
http://psc.apl.uw.edu/research/projects/arctic-sea-ice-volume-anomaly/data/.

This data set showcases the monthly changes in sea ice volume across the world from 1979 through present. The data is collected by The University of Washington’s Pan-Arctic Ice Ocean and Modeling System, or PIOMAS. This data set is in ASCII table format with 12 columns for each month and 44 rows for years 1979-present. The volume is 103 km3. Missing values are coded as -1, and it is updated monthly. The data set is available in text file and CSV file For this project, we plan to use import the csv version into R by calling read.csv().

### Greenhouse Gas Emission
https://www.climatewatchdata.org/data-explorer/historical-emissions?historical-emissions-data-sources=cait&historical-emissions-gases=All%20Selected%2Call-ghg&historical-emissions-regions=All%20Selected&historical-emissions-sectors=%2Ctotal-including-lucf&page=1#data

This data set showcases sector-level greenhouse gas (GHG) emissions for 194 countries and the European Union from 1990-2019. This data is updated regularly including emissions of the six major GHGs, Non-CO2 emissions
and other relevant metrics such as population and GDP values. This data set can be downloaded as a csv file, which is easy to import in R.

### Change in Mean Surface Temperature
https://www.fao.org/faostat/en/#data/ET 

This data set showcases the global mean surface temperature changes and its standard deviation by country. This data comes from the National Aeronautics and Space Administration Goddard Institute for Space Studies (NASA-GISS), and it is updated annually. The current statistics cover from 1961 to 2020 and are available for monthly. Like the previous data set, this can be downloaded as a csv file, and easily read into R Studios.

### Change in Forests
https://www.fao.org/faostat/en/#data/GF 

This data set showcases forests consists of CO2 emissions and removals corresponding to forest carbon stock changes. Statistics are available by country from 1990 to 2020. The data are based on United Nations Framework Convention on Climate Change (UNFCCC) and are sourced from the most recently available GHG National Inventories (NGHGI). It is updated annually and can be downloaded as a csv file, which is easy to import in R.

### Land Use
https://www.fao.org/faostat/en/#data/RL

This data set showcases the global land use in 46 categories, such as primary forest, agricultural practices and so on. Statistics are availbale by country from 1961 to 2020. The data are collected via the FAO Questionnaire on Land Use, Irrigation and Agricultural Practices, based on FAO Land Use classification. It is updated annually and can be downloaded as a csv file, which is easy to import in R

### Population
https://data.un.org/_Docs/SYB/CSV/SYB65_1_202209_Population,%20Surface%20Area%20and%20Density.csv

This data set showcases the population grouped by country in 2010, 2015, 2017, and 2022, including population estimates, sex ratio, population percentage in different age groups, population density, and surface area. The data comes from United Nations database and is updated recently. It can be downloaded as a csv file.

### Population growth
https://data.un.org/_Docs/SYB/CSV/SYB65_246_202209_Population%20Growth,%20Fertility%20and%20Mortality%20Indicators.csv

This data set showcases the population growth, fertility, life expectancy and mortality grouped by country in 2010, 2015, 2017, and 2022. The data also comes from United Nations database and is updated recently. It can be downloaded as a csv file.

### GDP
https://data.un.org/Data.aspx?q=gdp&d=SNAAMA&f=grID%3a101%3bcurrID%3aNCU%3bpcFlag%3a0

This data set showcases GDP by type of expenditure (including Final consumption expenditure, Household consumption expenditure, General government final consumption expenditure, etc.) at current prices grouped by country from 1970 to 2020. The data can be downloaded from United Nations database as a csv file and is updated annually.

### Air pollution
https://data.oecd.org/air/air-pollution-exposure.htm

The data set showcases the air pollution exposure by country until 2019. Air pollution exposure in the data refers to population exposure to more than 10 micrograms/m3 of Fine particulate matter (PM2.5). The data comes from Organisation for Economic Co-operation and Development (OECD) and can be downloaded as a csv file.





